# Routings
kb_config_index:
    path:     /kb_config/index
    methods:  [GET]
    defaults:
        _controller: 'PrestaShop\Module\Kb_Config\Controller\IndexController::indexAction'

# Routings
kb_config_add:
    path:     /kb_config/add
    methods:  [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\Kb_Config\Controller\IndexController::addAction'

